---
- hosts: nodes
  gather_facts: no

  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
      changed_when: False
    - setup:

  vars: 
    packages:
      - build-essential
      - dkms
      - unzip
      - wget
      - python-pip

  tasks:
    - name: Installing Pre-requisites packages
      apt: "pkg={{ item }} state=present update_cache=yes"
      become: yes
      with_items: "{{ packages }}"

    - name: Installing python packages requirements
      pip:
        name: "{{ item }}"
        state: present
        extra_args: "--upgrade"
      with_items:
        - pip
        - pexpect
      become: yes
      become_flags: "-E"
      register: pip_output
    
    - name: Add ansible repository
      apt_repository:
        repo: 'ppa:ansible/ansible'
        codename: 'xenial'
      become: yes
    
    - name: Install ansible
      apt:
        name: ansible
        state: present
        update_cache: yes
      become: yes

    - name: Adding vbox repository to sources.list
      lineinfile:
        path: /etc/apt/sources.list
        line: 'deb http://download.virtualbox.org/virtualbox/debian xenial contrib'
      become: yes

    - name: Adding apt-key for virtual box repository
      apt_key:
        url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
        state: present
      become: yes

    - name: Installing virtualbox 5.0
      apt:
        name: virtualbox-5.0
        update_cache: yes
        state: present
      become: yes

    - name: adding ubuntu to vboxusers grounp
      user:
        name: ubuntu
        groups: vboxusers
        append: yes
      become: yes

    - name: Make sure vboxdrv service is running
      systemd: 
        state: started
        name: vboxdrv
      become: yes

    - name: Check if vbox extension pack is installed
      command: VBoxManage list extpacks
      register: vboxext
      changed_when: false

    - name: Downloading Virtual Box extension pack
      get_url:
        url: http://download.virtualbox.org/virtualbox/5.0.24/Oracle_VM_VirtualBox_Extension_Pack-5.0.24-108355.vbox-extpack
        dest: /tmp/Oracle_VM_VirtualBox_Extension_Pack-5.0.24-108355.vbox-extpack
        force: no
      when: 'vboxext.stdout == "Extension Packs: 0"'

    - name: If needed install Virtual Box extension pack
      expect:
        command: VBoxManage extpack install /tmp/Oracle_VM_VirtualBox_Extension_Pack-5.0.24-108355.vbox-extpack
        responses: 
          'Do you agree to these license terms and conditions \(y/n\)\? ': "y"
      become: yes
      become_flags: "-E"
      when: 'vboxext.stdout == "Extension Packs: 0"'

    - name: Configure VitualBox User
      template:
        src: virtualbox.template
        dest: /etc/default/virtualbox
      become: yes
      register: vbox_config_changed

    - name: Restart vboxdrv
      systemd: 
        state: restarted
        name: vboxdrv
      become: yes
      when: vbox_config_changed.changed == True

    - name: Installing vagrant
      apt: "pkg=vagrant state=present update_cache=yes"
      become: yes
      