- hosts: nodes
  gather_facts: yes


  vars_prompt:
    - name: "githubuser"
      prompt: "Enter unityid"
      private: no
    - name: "githubpassword"
      prompt: "Enter token"
      private: yes

  tasks:
  - name: Install Maven If required
    apt: name=maven
    become: yes
  
  - name: Installing Pre-requisites packages
    apt: "pkg=python-pip state=present update_cache=yes"
    become: yes
  

  - name: Installing python packages requirements
    pip:
      name: "{{ item }}"
      state: present
      extra_args: "--upgrade"
    with_items:
      - pip
      - lxml
    become: yes
    become_flags: "-E"
    register: pip_output
  
  - name: Install python jenkins If required
    apt: name=python-jenkins
    become: yes
    become_flags: "-E"
  
  - name: Get crumb
    uri:
      url: 'http://localhost:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
      return_content: yes
    register: crumb

  - set_fact:
      id_name: "{{ 999999999999 | random | to_uuid }}"
      itrust_post_build_job_name: "itrust-post-build-job"
      itrust_build_job_name: "itrust_build_job"

  - name: Set credentials for github in jenkins
    uri:
      method: POST
      follow_redirects: all
      url: 'http://localhost:8080/credentials/store/system/domain/_/createCredentials'
      headers:
        Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
      body: |
        json={
          "": "0",
          "credentials": {
            # "scope": "GLOBAL",
            "id": "{{id_name}}",
            "username": "{{githubuser}}",
            "password": "{{githubpassword}}",
            "description": "My new credentials",
            "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
          }
        }
  
  - name: Copy ansible playbook for itrust post build job to jenkins server
    copy:
      src: 
      dest: /home/ubuntu/post-build/post-build-itrust.yml
    when: False
  
  - name: Copy inventory for post itrust build job to jenkins server
    copy:
      src: 
      dest: /home/ubuntu/post-build/inventory
    when: False

  - name: Set up Post Build Job for iTrust
    jenkins_job:
      config: "{{ lookup('template', 'templates/itrust_post_build_config.xml.j2') }}" 
      name: '{{itrust_post_build_job_name}}'
      url: http://localhost:8080

  - name: Set Up Build Job for iTrust
    jenkins_job:
      config: "{{ lookup('template', 'templates/itrust_config.xml.j2') }}"
      name: '{{itrust_build_job_name}}'
      url: http://localhost:8080
    
  - name: Restart jenkins
    systemd:
      state: restarted
      name: jenkins
    become: yes

  - name: Wait for Jenkins to start up
    uri:
      url: http://localhost:8080
      status_code: 200
      timeout: 5
    register: jenkins_service_status
    retries: 60
    delay: 5
    until: >
      'status' in jenkins_service_status and
      jenkins_service_status['status'] == 200

  