---
- name: Add master DNS host name in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{MASTER_IP}}  {{MASTER_DNS}} puppet"

- name: Add mater DNS host name in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ansible_host}} puppet.{{inventory_hostname}}.local"

- name: Download puppet
  get_url:
    url: https://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb
    dest: /tmp/

- name: Install Puppet package
  apt:
    deb: /tmp/puppetlabs-release-pc1-xenial.deb

- name: Run apt-get update
  apt:
    update_cache: yes
  changed_when: False

- name: Install puppet server
  apt:
    name: puppetserver
    state: present

- name: update puppet conf
  blockinfile:
    path: /etc/puppetlabs/puppet/puppet.conf
    block: |
      [main]
      certname = puppet.{{inventory_hostname}}.local
      server = {{MASTER_DNS}}
      environment = production
      [agent]
      runinterval = 600
  register: conf_updated

- name: restart puppet server
  shell: /opt/puppetlabs/bin/puppet resource service puppet ensure=running enable=true
  when: conf_updated.changed == True

- name: Register with master
  shell: /opt/puppetlabs/bin/puppet agent --test
  ignore_errors: True
  become: no
