var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc(-10,undefined);
subject.inc(10,false);
subject.weird(17,-10,32,"strict");
subject.weird(-3,10,52,false);
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.normalize('');
subject.normalize('');
subject.format('','','');
subject.format('','','');
subject.blackListNumber('');
subject.blackListNumber('');
