---
- hosts: locals
  gather_facts: false

  vars:
    vagrant_path: /home/ubuntu/vagrant_vm/checkboxio
    vagrant_key_path: /home/ubuntu/vagrant_vm/checkboxio/.vagrant/machines/default/virtualbox/private_key
    vagrant_ip: 192.168.33.20
    ansible_keys_dir: /home/ubuntu/post-build/keys

  tasks:

  - name: Create directory for vagrant vm
    file:
      path: "{{ vagrant_path }}"
      state: directory

  - name: Create vagrant init space
    copy:
      src: files/Vagrantfile_checkboxio
      dest: "{{ vagrant_path }}/Vagrantfile"
    become: yes

  - name: Create directory for vagrant ssh keys
    file:
      path: "{{ ansible_keys_dir }}"
      state: directory

  - name: Provision vm
    command: vagrant up
    args:
      chdir: "{{ vagrant_path }}"

  - name: Copy the vagrant key to required path
    copy:
      src: "{{ vagrant_key_path}}"
      dest: "{{ ansible_keys_dir }}/checkboxio.key" 
      mode: 0600

- hosts: checkboxio
  gather_facts: false

  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
      changed_when: False
    - setup:

  tasks:

  - name: Install node, npm, pip and build-essential
    apt:
      name: "{{ item }}"
      state: present
    become: yes
    with_items:
      - nodejs
      - npm
      - build-essential
      - python-pip
      - python3-pip

  - name: Deploy checkbox.io to remote server
    copy: 
      src: /var/lib/jenkins/workspace/checkbox/public_html
      dest: /vol/checkbox.io
      directory_mode: yes

  # - name: Import public key for mongodb
  #   apt_key:
  #     keyserver: keyserver.ubuntu.com
  #     id: EA312927
  #     state: present
  #     validate_certs: no
  #   become: yes

  # - name: Add mongodb source
  #   apt_repository:
  #     repo: deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse"
  #     #repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse
  #     state: present
  #   become: yes

  # - name: Update packages
  #   apt:
  #     update_cache: yes
  #   become: yes

  # - name: Install mongodb, nginx, node, build-essential, npm
  #   apt:
  #     name: "{{ item }}"
  #     state: present
  #     allow_unauthenticated: yes
  #   with_items:
  #     - mongodb
  #     - nginx
  #     - nodejs
  #     - build-essential
  #     - npm
  #   become: yes

  # - name: install pymongo
  #   pip:
  #     name: pymongo
  #     state: present


  # - name: Create a mongodb service
  #   copy:
  #     src: files/mongodb.service
  #     dest: /etc/systemd/system
  #   become: yes

  # - name: Start mongodb service and make it available after bootup
  #   service:
  #     name: mongodb
  #     state: started
  #     enabled: yes
  #   become: yes

  # - name: Add admin user to mongodb
  #   mongodb_user:
  #     database: admin
  #     name: admin
  #     password: "{{ mongodb_password }}"
  #     state: present
  #     roles: userAdminAnyDatabase
  #   become: yes

  # - name: Restart mongodb service
  #   service:
  #     name: mongodb
  #     state: restarted
  #   become: yes

  # - name: Set mongodb environment variables
  #   blockinfile:
  #     path: /etc/environment
  #     block: |
  #       MONGO_PORT="3002"
  #       MONGO_IP="127.0.0.1"
  #       MONGO_USER="admin"
  #       MONGO_PASSWORD="{{ mongodb_password }}"
  #       MAIL_USER="devops.adaa@gmail.com"
  #       MAIL_PASSWORD="{{ mail_password }}"
  #       MAIL_SMTP="mock"
  #     marker: "# {mark} ANSIBLE MANAGED BLOCK"
  #   become: yes


  # - name: Remove default config of checkbox
  #   file:
  #     state: absent
  #     path: /etc/nginx/sites-available/default
  #   become: yes

  # - name: Remove default config symlink of checkbox
  #   file:
  #     state: absent
  #     path: /etc/nginx/sites-enabled/default
  #   become: yes

  # - name: Make checkbox available in nginx server
  #   copy:
  #     src: files/checkbox.io
  #     dest: /etc/nginx/sites-available
  #   become: yes

  # - name: Enable checkbox.io in nginx server
  #   file:
  #     src: /etc/nginx/sites-available/checkbox.io
  #     dest: /etc/nginx/sites-enabled/checkbox.io
  #     state: link
  #   become: yes

  # - name: Restart nginx
  #   service:
  #     name: nginx
  #     state: restarted
  #   become: yes

  # # - name: Restart server
  # #   become: yes
  # #   shell: sleep 2 && /sbin/shutdown -r now "Reboot for updates"
  # #   async: 1
  # #   poll: 0

  # # - name: Waiting for server to come back
  # #   become: true
  # #   local_action: wait_for host={{ inventory_hostname }} state=started port=22 timeout=600 connect_timeout=15 delay=300

  # # - name: Up checkbox.io
  # #   command: nodejs server.js
  # #   args:
  # #     chdir: /vol/checkbox.io/server-side/site


