#!/bin/sh
#
# An hook script to run after each commit.
# This will open a web browser "Google Chrome" and open "http://www.google.com"
#

/usr/bin/open -a "/Applications/Google Chrome.app" 'http://www.google.com'
