--- # Build Job for Useless Test Detector

- name: Checking if useless test detector job already exists
  shell: "java -jar /home/jenkins-cli.jar -s http://localhost:8080 list-jobs --username {{username}} --password {{jenkinspassword}}"
  register: jobs_list
  changed_when: "jobs_list.stdout.find('itrust-useless-test') == -1"

- name: Sending template for iTrust Useless test detector to Jenkins server
  copy:
    src: files/useless.xml
    dest: /tmp/useless.xml
  when: "jobs_list.stdout.find('itrust-useless-test') == -1"

- name: create a direcotory for placing useless scripts
  file:
    path: "/var/lib/jenkins/useless"
    state: directory
    owner: jenkins
    mode: 0755

- name: Copy useless test detector python script to jenkins server
  copy:
    src: files/uselessTest.py
    dest: "{{jenkins_home}}/useless/uselessTest.py"
    owner: jenkins
    force: yes

- name: Creating new build job for useless test detector
  shell: java -jar /home/jenkins-cli.jar -auth "{{username}}":"{{jenkinspassword}}" -s http://localhost:8080 create-job itrust-useless-test < /tmp/useless.xml
  when: "jobs_list.stdout.find('itrust-useless-test') == -1"
