---
ufwports:
  - 22 # TO allow SSH
  - 8080 # For Jenkins
packages:
  - gcc
  - git
  - git-core
  - python-dev
  - python-mysqldb
  - libmysqlclient-dev
  - python-setuptools
  - mysql-server
  - oracle-java8-installer
  - oracle-java8-set-default
  - maven
  - python-software-properties
plugins:
  - junit
  - postbuild-task
  - jacoco
  - test-stability
  - git
  - git-client
  - git-server
  - maven-plugin
  - build-timeout