---
- hosts: nodes
  gather_facts: no

  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

  vars: 
    packages:
      - build-essential
      - dkms
      - unzip
      - wget
      - python-pip

  tasks: 
    - name: Gathering facts
      setup:


    - name: Updating packages cache
      apt:
        update_cache: yes
      become: yes

    # - name: Updating Ubuntu Server
    #   apt:
    #     upgrade: yes
    #   become: yes

    - name: Installing Pre-requisites packages
      apt: "pkg={{ item }} state=present update_cache=yes"
      become: yes
      with_items: "{{ packages }}"

    - name: Installing python packages requirements
      pip:
        name: pexpect
        state: present

    - name: Adding vbox repository to sources.list
      lineinfile:
        path: /etc/apt/sources.list
        line: 'deb http://download.virtualbox.org/virtualbox/debian xenial contrib'
      become: yes

    - name: Adding apt-key for virtual box repository
      apt_key:
        url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
        state: present
      become: yes

    - name: Installing virtualbox 5.0
      apt:
        name: virtualbox-5.0
        update_cache: yes
        state: present
      become: yes

    - name: adding ubuntu to vboxusers grounp
      user:
        name: ubuntu
        groups: vboxusers
        append: yes
      become: yes

    - name: Make sure vboxdrv service is running
      systemd: 
        state: started
        name: vboxdrv
      become: yes

    - name: Check if vbox extension pack is installed
      command: VBoxManage list extpacks
      register: vboxext
      changed_when: false

    - name: Downloading Virtual Box extension pack
      get_url:
        url: http://download.virtualbox.org/virtualbox/5.0.24/Oracle_VM_VirtualBox_Extension_Pack-5.0.24-108355.vbox-extpack
        dest: /tmp/Oracle_VM_VirtualBox_Extension_Pack-5.0.24-108355.vbox-extpack
        force: no
      when: 'vboxext.stdout == "Extension Packs: 0"'

    - name: If needed install Virtual Box extension pack
      expect:
        command: VBoxManage extpack install /tmp/Oracle_VM_VirtualBox_Extension_Pack-5.0.24-108355.vbox-extpack
        responses: 
          'Do you agree to these license terms and conditions \(y/n\)\? ': "y"
      become: yes
      become_flags: "-E"
      when: 'vboxext.stdout == "Extension Packs: 0"'

    - name: Installing Pre-requisites for php-virtual box
      apt: "pkg={{ item }} state=present update_cache=yes"
      become: yes
      with_items: 
        - apache2
        - php
        - php-mysql
        - libapache2-mod-php
        - php-soap
        - php-xml

    - name: Make sure webdir for phpVirtualBox exists
      file:
        path: /var/www/html/
        state: directory

    - name: Check if phpVirtualBox is already installed
      stat:
        path: /var/www/html/phpvirtualbox
      register: phpbox_installed

    - name: Downloading phpVirtualBox
      get_url:
        url: https://sourceforge.net/projects/phpvirtualbox/files/phpvirtualbox-5.0-5.zip
        dest: /tmp/phpvirtualbox-5.0-5.zip
        force: no
      when: phpbox_installed.stat.exists == False

    - name: Unzip phpVirtualBox
      unarchive:
        src: /tmp/phpvirtualbox-5.0-5.zip
        dest: /tmp/
        mode: 0777
        remote_src: yes
      become: yes
      when: phpbox_installed.stat.exists == False

    - name: Installing phpVirtualBox
      synchronize:
        src: '/tmp/phpvirtualbox-5.0-5/'
        dest: '/var/www/html/phpvirtualbox/'
        recursive: yes
        perms: yes
      become: yes
      delegate_to: "{{ inventory_hostname }}"
      when: phpbox_installed.stat.exists == False

    - name: Configure phpVirtualBox
      copy:
        src: templates/config.php.template
        dest: /var/www/html/phpvirtualbox/config.php
        owner: root
        group: root
        mode: 0644
      become: yes
      register: php_config_changed

    - name: Configure VitualBox User
      copy:
        src: templates/virtualbox.template
        dest: /etc/default/virtualbox
        owner: root
        group: root
        mode: 0644    
      become: yes
      register: vbox_config_changed

    - name: Restart vboxweb-service
      systemd: 
        state: restarted
        name: vboxweb-service
      become: yes
      when: php_config_changed.changed == True or vbox_config_changed.changed == True

    - name: Restart vboxdrv
      systemd: 
        state: restarted
        name: vboxdrv
      become: yes
      when: php_config_changed.changed == True or vbox_config_changed.changed == True

    - name: Restart apache2
      systemd: 
        state: restarted
        name: apache2
      become: yes
      when: php_config_changed.changed == True or vbox_config_changed.changed == True

