---
- hosts: nodes

  tasks:
    - name: Create VMs Home directory if needed
      file:
        path: /home/{{ ansible_ssh_user }}/VagrantVMs/
        state: directory
        mode: 0755

    - name: Create a new folder for new VM
      file:
        path: /home/{{ ansible_ssh_user }}/VagrantVMs/{{ 999999999999 | random | to_uuid }}
        state: directory
        mode: 0755
      register: new_folder_vm

    - name: initialize a new ubuntu trusty 32 bit VM
      copy:
        src: templates/Vagrantfile_template
        dest: '{{ new_folder_vm.diff.after.path }}/Vagrantfile'
      register: initialized

    - name: start the newly created VM
      command: vagrant up
      args:
        chdir: '{{ new_folder_vm.diff.after.path }}'
      register: vag_start_output

    - debug:
        var: vag_start_output