---
- hosts: nodes
  remote_user: root
  sudo: yes

  vars_prompt:
  - name: "gituser"
    prompt: "Enter Unity Id"
    private: no

  - name: "gitpass"
    prompt: "Enter Token"
    private: yes


  tasks:
  - name: apt update
    apt: update_cache=yes cache_valid_time=3600
    register: apt_result
    until: apt_result|success
    retries: 3
    delay: 1
    sudo: yes
    ignore_errors: yes

  - name: retry if needed using command apt-get update
    command: apt-get update
    sudo: yes
    when: apt_result|failed
      

  - name: install Java
    apt_repository:
                repo: 'ppa:webupd8team/java'


  - name: agree to oracle license terms and conditions
    shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
    sudo: yes

  - name: install java8
    shell: apt install -y oracle-java8-installer ca-certificates
    sudo: yes


  - name: Install Maven If required
    apt: name=maven
    become: yes

  - name: install maven (and other packages if needed)
    become: yes
    apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
    with_items:
      - maven

  - name: change password for mysql
    debconf: name=mysql-server question=mysql-server/root_password value=123456 vtype='password'

  - name: retype password for mysql
    debconf: name=mysql-server question=mysql-server/root_password_again value=123456 vtype='password'

  - name: Install required system packages
    apt: pkg={{ item }} state=present
    with_items:
      - libmysqlclient-dev
      - python-dev
      - python-pip
      - gcc
      - python-setuptools
      - mysql-server
      - git-core
      - mysql-client
      - python-setuptools
      - python-mysqldb
    become: yes


  - name: ensure mysql is running and starts on boot
    service: name=mysql state=started enabled=true

  - name: Install - MySQL-python
    pip: name=MySQL-python
    become: yes

  - name: Remove MySQL case sensitivity
    copy: src=my.cnf dest=/etc/mysql

  - name: Restart MySQL service
    service: name=mysql state=restarted

  - name: download Tomcat
    get_url: url=http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.0.M17/bin/apache-tomcat-9.0.0.M17.tar.gz dest=/opt/

  - name: make tomcat9 dir
    become_user: root
    shell: sudo mkdir -p tomcat9
    args:
      chdir: /opt

  - name: unzip Tomcat
    unarchive: src=/opt/apache-tomcat-9.0.0.M17.tar.gz dest=/opt/tomcat9 remote_src=True

  - name: Configure tomcat environment variables
    become_user: root
    script: config.sh

  - name: Configure Tomcat users
    template: src=tomcat-users.xml dest=/opt/tomcat9/apache-tomcat-9.0.0.M17/conf/

  - name: Install Tomcat init script
    copy: src=init.sh dest=/etc/init.d/tomcat mode=0755

  - name: Remove permissions on tomcat
    copy: src=context.xml dest=/opt/tomcat9/apache-tomcat-9.0.0.M17/webapps/manager/META-INF

  - name: Start Tomcat
    service: name=tomcat state=started enabled=yes

  - name: Remove MySQL case sensitivity
    copy: src=my.cnf dest=/etc/mysql

  - name: Restart MySQL service
    service: name=mysql state=restarted

  - name: copying manager.xml
    copy: src=manager.xml dest=/opt/tomcat9/apache-tomcat-9.0.0.M17/conf/Catalina/localhost

  - name: Maven settings
    copy: src=settings.xml dest=/usr/share/maven/conf


  - name: Install git
    apt: name=git state=present
  
  - name: git clone
    become_user: root
    git: repo=https://{{ gituser }}:{{ gitpass }}@github.ncsu.edu/engr-csc326-staff/iTrust-v23.git dest=/root/iTrust-v23

  - name: Maven package - change directory to iTrust before that
    become_user: root
    script: mvn.sh

  - name: deploy maven - change directory to iTrust before that
    become_user: root
    shell: mvn tomcat7:deploy
    args:
      chdir: /root/iTrust-v23/iTrust

